<div class="content-header"><h3>Welcome</h3></div>
<p>Welcome to the J\IV admin interface. </p>
<p>J\IV is simple, powerful self-contained tabbing software.</p>
<p>From here you can set up your IV: add rooms, teams, speaks, rounds and info slides.</p>
<p>There's a <a href="/?x=home_walkthru">tutorial walkthrough</a> to get you started,
and it serves as a reference if you get lost.</p>
<p>You should read the walkthrough in its (small) entireity before using this software for the first time!</p>