<div class="content-header"><h3>Tutorial</h3></div>
<p>J\IV is sophisticated yet very simple IV tabbing software.</p>
<p>The basic proceedure is very simple, select the + (add) sign next to Rooms, add all of your competition rooms. </p>
<p>Do the same with teams, ajudicators and the schedule and click Start under show. If you make a mistake you can click on the 
- (delete) link or view the entry by selecting the index page, (the Rooms, Teams, etc. links).</p>
<p>Select the &lt;!&gt; link next to Tab Speaks to distribute everyone to the rooms. After a round select the Tab Speaks link to eneter the speaker points 
- they can always be changed, even after clicking &lt;!&gt;. Just open the page again and select the distribute link (&lt;!&gt;) again.</p>
<p>For each subsequent round just click Current Round to get to the appropriate slides.</p>
<p>When viewing the slideshow press F11. This will give you a powerpoint-like fullscreen view of the page. 
The best effect is found with later version of internet explorer (7, 8; turn off the status bar, (press alt) > view > toolbars > status bar) and Chrome.</p>
<p>If you want to send the slides to a different PC, select the [P] link and send the pdf file (via email, etc.). When viewing PDFs press Ctrl and L to make them fullscreen. The slides wont move automatically in this case and you will need to press the Right keyboard arrow appropriatly. </p>
<p>However there is also a staffing feature to keep track of behind-the-scenes who-is-doing-what, which you can generate slides for 
- perhaps to provide the competitors with staff information should they need to speak to someone.</p>
<p>You can also generate a register slide, for reading out after breaks, to make sure everyone is back.</p>
<p>The Options link also provides a varitey of novel configuration options. 
By default the first room you enter is used to host the highest-tabbing rooms, the second room the second highest-tabbing and so on. 
You can also use the rooms randomly by selecting the appropriate check box.</p>
<p>The slide show should also be configured from the options section.</p>
<p>Adjudicators are also, by default, ranked and assigned so that highest ranking go to the best rooms. This can be made random; it might be useful to make the distribution random for the first two or three rounds, and then let the latter rounds be most expertly judged.</p>
<p>Therefore it is a <strong>very</strong> good idea to rank the CA/DCAs/Chairs starting from 100 down (regardless of whether wings may be better judges!) since the Rank is how they are selected (for chairing!).</p>
<p>By selecting the Ajudicators link you can edit adjudicators and increase the rank of selected wings (given feedback). To remove an adjudicator (following a complaint, for example) just select the - (delete link); he or she can always be added again before the next round.</p>
<p>The 'Publish Tab' option can send the compeition information to Google Docs, and also generate a pdf or csv (for excel, etc.) if you want to provide the information another way.</p>
